'''
@author:   Ken Venner
@contact:  ken@venerllc.com
@version:  1.02

Tool used to extract attune/auteur records from winetoday.csv and mail out
that report to interested parties
'''

### TODO - add the optiondict in this and command line processing

import kvcsv
import kvgmailsend

import re

# logging
import os
import logging
# Logging Setup
# logging.basicConfig(level=logging.INFO)
logging.basicConfig(filename=os.path.splitext(os.path.basename(__file__))[0]+'.log',
                    level=logging.INFO,
                    format='%(asctime)s - %(name)s - %(threadName)s -  %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


# local variables
re_wine = re.compile('Attune|Auteur',re.IGNORECASE)

srcfile = 'winetoday.csv'
destfile = 'winetodayattune.csv'

fromaddr = 'wines@vennerllc.com'
password = 'win3s3arch*'

email_to_list = ['ken@vennerllc.com', 'mscribner@bcciconst.com', 'kenneth@auteurwines.com', 'laura@auteurwines.com']

# used for testing - we should have a testing flag when we put in the options
# and when set - change the email_to_list ot this.
# email_to_list= ['ken@vennerllc.com']

# logging message
logger.info('read in:%s', srcfile)

# create the attachment we are sending out
winetoday = kvcsv.readcsv2list(srcfile)
wineattune = [rec for rec in winetoday if re_wine.match(rec['Wine'])]
kvcsv.writelist2csv(destfile, wineattune)

# logging message
logger.info('write to:%s',destfile)

# create email and send out attachment
m = kvgmailsend.GmailSend(fromaddr, password)
m.addRecipients(email_to_list)
m.setSubject('Auteur/Attune Web Pricing Report')
m.setTextBody('Attached is a report showing pricing for Auteur and Attune on the internet\n\nMessage generated by:  wineattune.py')
m.addAttachment(destfile)
m.send()
# m.quit()

# logging message
logger.info('report sent out to:%s', email_to_list)

#eof
