import kvcsv
import re
import kvgmailsend

# local variables
re_wine = re.compile('Attune|Auteur',re.IGNORECASE)

srcfile = 'winetoday.csv'
destfile = 'winetodayattune.csv'

fromaddr = 'wines@vennerllc.com'
password = 'win3s3arch*'

email_to_list = ['ken@vennerllc.com', 'mscribner@bcciconst.com', 'kenneth@auteurwines.com', 'laura@auteurwines.com']

# create the attachment we are sending out
winetoday = kvcsv.readcsv2list(srcfile)
wineattune = [rec for rec in winetoday if re_wine.match(rec['Wine'])]
kvcsv.writelist2csv(destfile, wineattune)

# create email and send out attachment
m = kvgmailsend.GmailSend(fromaddr, password)
m.addRecipients(email_to_list)
m.setSubject('Auteur/Attune Web Pricing Report')
m.setTextBody('Attached is a report showing pricing for Auteur and Attune on the internet\n\nMessage generated by:  wineattune.py')
m.addAttachment(destfile)
m.send()
m.quit()
